name: pc-desktop
version: '22-0.3'
type: gadget
build-base: core22
base: core22-desktop
summary: PC gadget for generic devices
description: |
    This gadget enables generic pc devices to work with Ubuntu Core Desktop
confinement: strict
grade: stable
architectures:
  - build-on: amd64
    build-for: amd64

assumes:
  - snapd2.59.3

parts:
  extra:
    stage-snaps: [pc/22/stable]
    source: ./extra
    plugin: dump
